name: Code_Quality

on:
  pull_request:
    branches:
      - main # Run on PR against main branch.

jobs:
  linter:
    name: Lint code
    runs-on: ubuntu-latest # Run on Ubuntu server.
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint

  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest # Run on Ubuntu server.
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: node src/tests/MyUnitTest.js
